### ISSUE TITLE
Bot threw an exception when Slack returned a non-200 response

### ISSUE THREAD

**Issue by CptSpaceToaster** [CptSpaceToaster/yeti#1]
Slack-logging was enabled.

I'm not 100% sure what the cause was, but it might have been a hiccup in the tubes, or slack rate-limiting the incoming-webhook for some reason.

```
Traceback (most recent call last):
  File "./yeti.py", line 40, in <module>
    jabber.do_chat()
  File "/home/arlx/Github/yeti/chat.py", line 78, in do_chat
    slack_msg(msg.user, msg.text)
  File "/home/arlx/Github/yeti/chat.py", line 124, in slack_msg
    share.log("Error: " + r.status_code + " " + r.reason + " - " + r.text)
TypeError: Can't convert 'int' object to str implicitly
```

**Comment by CptSpaceToaster** [comment]
I'll reopen the issue if it resurfaces again.
